# Data Wrangling

# Gather

In [ ]:
import pandas as pd
import requests
import re

In [2]:
# the code solution below downloads the .tsv file from the url.
# This solution was found at https://www.kite.com/python/answers/how-to-download-a-csv-file-from-a-url-in-python

url = 'https://d17h27t6h515a5.cloudfront.net/topher/2017/August/599fd2ad_image-predictions/image-predictions.tsv'
req = requests.get(url)
url_content = req.content
csv_file = open('image-predictions.tsv', 'wb')

csv_file.write(url_content)
csv_file.close()

In [3]:
#reads .tsv file downloaded above, sets it to dataframe 'df_image_predictions'

df_image_predictions = pd.read_csv('image-predictions.tsv', sep='\t')

In [4]:
# initial look at df_image_predictions
df_image_predictions.head()

,tweet_id,jpg_url,img_num,p1,p1_conf,p1_dog,p2,p2_conf,p2_dog,p3,p3_conf,p3_dog
0,666020888022790149,https://pbs.twimg.com/media/CT4udn0WwAA0aMy.jpg,1,Welsh_springer_spaniel,0.465074,True,collie,0.156665,True,Shetland_sheepdog,0.061428,True
1,666029285002620928,https://pbs.twimg.com/media/CT42GRgUYAA5iDo.jpg,1,redbone,0.506826,True,miniature_pinscher,0.074192,True,Rhodesian_ridgeback,0.072010,True
2,666033412701032449,https://pbs.twimg.com/media/CT4521TWwAEvMyu.jpg,1,German_shepherd,0.596461,True,malinois,0.138584,True,bloodhound,0.116197,True
3,666044226329800704,https://pbs.twimg.com/media/CT5Dr8HUEAA-lEu.jpg,1,Rhodesian_ridgeback,0.408143,True,redbone,0.360687,True,miniature_pinscher,0.222752,True
4,666049248165822465,https://pbs.twimg.com/media/CT5IQmsXIAAKY4A.jpg,1,miniature_pinscher,0.560311,True,Rottweiler,0.243682,True,Doberman,0.154629,True

In [5]:
# creates dataframe from twitter_archive_enhanced.csv, saves to "df_twitter_archive"

df_twitter_archive = pd.read_csv(r'C:\Users\14802\Desktop\DATA_PROJECTS\udacity_projects\Project_4_Data_Wrangling\datasets\twitter-archive-enhanced.csv')

In [6]:
# initial look at df_twitter_archive

df_twitter_archive.head()

,tweet_id,in_reply_to_status_id,in_reply_to_user_id,timestamp,source,text,retweeted_status_id,retweeted_status_user_id,retweeted_status_timestamp,expanded_urls,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo
0,892420643555336193,NaN,NaN,2017-08-01 16:23:56 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Phineas. He's a mystical boy. Only eve...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/892420643...,13,10,Phineas,None,None,None,None
1,892177421306343426,NaN,NaN,2017-08-01 00:17:27 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Tilly. She's just checking pup on you....,NaN,NaN,NaN,https://twitter.com/dog_rates/status/892177421...,13,10,Tilly,None,None,None,None
2,891815181378084864,NaN,NaN,2017-07-31 00:18:03 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Archie. He is a rare Norwegian Pouncin...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891815181...,12,10,Archie,None,None,None,None
3,891689557279858688,NaN,NaN,2017-07-30 15:58:51 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Darla. She commenced a snooze mid meal...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891689557...,13,10,Darla,None,None,None,None
4,891327558926688256,NaN,NaN,2017-07-29 16:00:24 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Franklin. He would like you to stop ca...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891327558...,12,10,Franklin,None,None,None,None

In [8]:
df_twitter_archive['tweet_id']

0       892420643555336193
1       892177421306343426
2       891815181378084864
3       891689557279858688
4       891327558926688256
               ...
2351    666049248165822465
2352    666044226329800704
2353    666033412701032449
2354    666029285002620928
2355    666020888022790149
Name: tweet_id, Length: 2356, dtype: int64

In [9]:
df_image_predictions['tweet_id']

0       666020888022790149
1       666029285002620928
2       666033412701032449
3       666044226329800704
4       666049248165822465
               ...
2070    891327558926688256
2071    891689557279858688
2072    891815181378084864
2073    892177421306343426
2074    892420643555336193
Name: tweet_id, Length: 2075, dtype: int64

In [10]:
tweet_ids = df_image_predictions['tweet_id']

In [11]:
tweet_ids = pd.DataFrame(data=tweet_ids)

In [12]:
tweet_ids

                tweet_id
0     666020888022790149
1     666029285002620928
2     666033412701032449
3     666044226329800704
4     666049248165822465
...                  ...
2070  891327558926688256
2071  891689557279858688
2072  891815181378084864
2073  892177421306343426
2074  892420643555336193

[2075 rows x 1 columns]

In [13]:
tweet_ids_csv = tweet_ids.to_csv('datasets/tweet_ids.csv', index=False)

In [14]:
tweet_ids

                tweet_id
0     666020888022790149
1     666029285002620928
2     666033412701032449
3     666044226329800704
4     666049248165822465
...                  ...
2070  891327558926688256
2071  891689557279858688
2072  891815181378084864
2073  892177421306343426
2074  892420643555336193

[2075 rows x 1 columns]

In [15]:
import json
import tweepy
import asyncio
from Constants import api

errors = []

# function requests tweets by tweet ids found in other dataframe from Twitter API
# API authentication was done in other file (Constants.py) to hide keys and tokens 

async def get_tweets():
    index = 0
    tweet_index = 0
    
    with open('tweets_json.txt', 'w') as outfile:

        while index < 2076:
            
        # uses asyncio to wait 15 minutes between each request due to twitter api rate limits
            if index == 900: 
                print('entered 900 sleep')
                await asyncio.sleep(960) 
                
            if index == 1800:
                print('entered 1800 sleep')
                await asyncio.sleep(900)
          
        # in a try/catch to send ids to an errors list in case any ids have been deleted and can no longer be retrieved 
            try: 
                tweets_to_get = tweet_ids['tweet_id'][tweet_index]
                tweets = api.get_status(tweets_to_get, tweet_mode='extended')
                
        # writes responses in json format in a txt file        
                json.dump(tweets._json, outfile)
                outfile.write('\n')
                print("Request successful!")
                tweet_index += 1
                index += 1
                
        # creates a list of errors to be referenced later on to know which id's from the dataframes were unavailable
            except tweepy.TweepError as err:
                errors.append(tweets_to_get)
                tweet_index += 1
                index += 1
                print("ID not found")
                
            pass

## <span style="color:red"> STOP -</span>

#### <span style="color:red"> Cell below takes approx 30 min to run - do not rerun if tweets_json.txt is already available. </span>

In [16]:
# asyncio typically runs into errors in jupyter notebook due to the kernel continuously running 
# big shoutout to Vinicuis Fortuna on GitHub providing this workaround 
# https://github.com/ipython/ipython/issues/11030#issuecomment-377723960

asyncio.run_coroutine_threadsafe(get_tweets(), asyncio.get_event_loop())

Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!

Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!

Rate limit reached. Sleeping for: 729

Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
ID not found
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
entered 900 sleep
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!

Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
ID not found
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!

Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
ID not found
Request successful!
Request successful!
ID not found
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
ID not found
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
ID not found
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
ID not found
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!

Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
ID not found
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
entered 1800 sleep
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
ID not found
Request successful!
ID not found
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
ID not found
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
ID not found
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
ID not found
ID not found
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
ID not found
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
ID not found
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
ID not found
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
ID not found
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!
Request successful!

In [17]:
# ensures id's which were not found are saved to 'errors' list
errors

[680055455951884288,
 754011816964026368,
 759566828574212096,
 759923798737051648,
 771004394259247104,
 779123168116150273,
 802247111496568832,
 829374341691346946,
 837012587749474308,
 837366284874571778,
 842892208864923648,
 844704788403113984,
 851861385021730816,
 851953902622658560,
 861769973181624320,
 872261713294495745,
 873697596434513921,
 888202515573088257]

In [19]:
# saves errors to new variable with more descriptive name

ids_to_delete = errors.copy()

In [22]:
# reads txt file

with open('tweets_json.txt') as file:
    json_tweets = []
    for line in file:
        json_tweets.append(line)

In [26]:
# extracts tweet_id, retweet count, and favorite count from the json objects in txt file

tweet_list = []
for tweet in json_tweets:
    tweet_id = json.loads(tweet)['id']
    retweet_count = json.loads(tweet)['retweet_count']
    favorite_count = json.loads(tweet)['favorite_count']
    tweet_list.append({'tweet_id': tweet_id, 'retweet_count': retweet_count, 'favorite_count':favorite_count})

In [29]:
# creates dataframe from json objects extracted above

api_tweets_df = pd.DataFrame(tweet_list, columns = ['tweet_id', 'retweet_count', 'favorite_count'])

# Assess

## Visual Assessment

First I will take an overview visual look at all three dataframes.

In [34]:
df_image_predictions

,tweet_id,jpg_url,img_num,p1,p1_conf,p1_dog,p2,p2_conf,p2_dog,p3,p3_conf,p3_dog
0,666020888022790149,https://pbs.twimg.com/media/CT4udn0WwAA0aMy.jpg,1,Welsh_springer_spaniel,0.465074,True,collie,0.156665,True,Shetland_sheepdog,0.061428,True
1,666029285002620928,https://pbs.twimg.com/media/CT42GRgUYAA5iDo.jpg,1,redbone,0.506826,True,miniature_pinscher,0.074192,True,Rhodesian_ridgeback,0.072010,True
2,666033412701032449,https://pbs.twimg.com/media/CT4521TWwAEvMyu.jpg,1,German_shepherd,0.596461,True,malinois,0.138584,True,bloodhound,0.116197,True
3,666044226329800704,https://pbs.twimg.com/media/CT5Dr8HUEAA-lEu.jpg,1,Rhodesian_ridgeback,0.408143,True,redbone,0.360687,True,miniature_pinscher,0.222752,True
4,666049248165822465,https://pbs.twimg.com/media/CT5IQmsXIAAKY4A.jpg,1,miniature_pinscher,0.560311,True,Rottweiler,0.243682,True,Doberman,0.154629,True
...,...,...,...,...,...,...,...,...,...,...,...,...
2070,891327558926688256,https://pbs.twimg.com/media/DF6hr6BUMAAzZgT.jpg,2,basset,0.555712,True,English_springer,0.225770,True,German_short-haired_pointer,0.175219,True
2071,891689557279858688,https://pbs.twimg.com/media/DF_q7IAWsAEuuN8.jpg,1,paper_towel,0.170278,False,Labrador_retriever,0.168086,True,spatula,0.040836,False
2072,891815181378084864,https://pbs.twimg.com/media/DGBdLU1WsAANxJ9.jpg,1,Chihuahua,0.716012,True,malamute,0.078253,True,kelpie,0.031379,True
2073,892177421306343426,https://pbs.twimg.com/media/DGGmoV4XsAAUL6n.jpg,1,Chihuahua,0.323581,True,Pekinese,0.090647,True,papillon,0.068957,True
2074,892420643555336193,https://pbs.twimg.com/media/DGKD1-bXoAAIAUK.jpg,1,orange,0.097049,False,bagel,0.085851,False,banana,0.076110,False

- missing values / NaN
- "p1", "p2", "p3" / breed columns - casing and spaces not uniform

In [35]:
df_twitter_archive

,tweet_id,in_reply_to_status_id,in_reply_to_user_id,timestamp,source,text,retweeted_status_id,retweeted_status_user_id,retweeted_status_timestamp,expanded_urls,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo
0,892420643555336193,NaN,NaN,2017-08-01 16:23:56 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Phineas. He's a mystical boy. Only eve...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/892420643...,13,10,Phineas,None,None,None,None
1,892177421306343426,NaN,NaN,2017-08-01 00:17:27 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Tilly. She's just checking pup on you....,NaN,NaN,NaN,https://twitter.com/dog_rates/status/892177421...,13,10,Tilly,None,None,None,None
2,891815181378084864,NaN,NaN,2017-07-31 00:18:03 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Archie. He is a rare Norwegian Pouncin...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891815181...,12,10,Archie,None,None,None,None
3,891689557279858688,NaN,NaN,2017-07-30 15:58:51 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Darla. She commenced a snooze mid meal...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891689557...,13,10,Darla,None,None,None,None
4,891327558926688256,NaN,NaN,2017-07-29 16:00:24 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Franklin. He would like you to stop ca...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891327558...,12,10,Franklin,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2351,666049248165822465,NaN,NaN,2015-11-16 00:24:50 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here we have a 1949 1st generation vulpix. Enj...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666049248...,5,10,None,None,None,None,None
2352,666044226329800704,NaN,NaN,2015-11-16 00:04:52 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a purebred Piers Morgan. Loves to Netf...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666044226...,6,10,a,None,None,None,None
2353,666033412701032449,NaN,NaN,2015-11-15 23:21:54 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here is a very happy pup. Big fan of well-main...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666033412...,9,10,a,None,None,None,None
2354,666029285002620928,NaN,NaN,2015-11-15 23:05:30 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a western brown Mitsubishi terrier. Up...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666029285...,7,10,a,None,None,None,None
2355,666020888022790149,NaN,NaN,2015-11-15 22:32:08 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here we have a Japanese Irish Setter. Lost eye...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666020888...,8,10,None,None,None,None,None

- missing values - NaN
- tweet ids are listed in descending order (other two dataframes are listed in tweet id ascending order)
- the name column has some weird values such as "None" and "a" - si they are essentially null even though they don't appear as NaN

In [36]:
api_tweets_df

                tweet_id  retweet_count  favorite_count
0     666020888022790149            427            2315
1     666029285002620928             39             115
2     666033412701032449             36             101
3     666044226329800704            117             249
4     666049248165822465             37              90
...                  ...            ...             ...
2052  891327558926688256           7826           35641
2053  891689557279858688           7280           37302
2054  891815181378084864           3517           22306
2055  892177421306343426           5344           29626
2056  892420643555336193           7086           34160

[2057 rows x 3 columns]

## Programmatic Assessment

Now I'll use programmatic assessment to identify potential quality and/or tidiness issues.

In [37]:
df_image_predictions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2075 entries, 0 to 2074
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   tweet_id  2075 non-null   int64
 1   jpg_url   2075 non-null   object
 2   img_num   2075 non-null   int64
 3   p1        2075 non-null   object
 4   p1_conf   2075 non-null   float64
 5   p1_dog    2075 non-null   bool
 6   p2        2075 non-null   object
 7   p2_conf   2075 non-null   float64
 8   p2_dog    2075 non-null   bool
 9   p3        2075 non-null   object
 10  p3_conf   2075 non-null   float64
 11  p3_dog    2075 non-null   bool
dtypes: bool(3), float64(3), int64(2), object(4)
memory usage: 152.1+ KB

- column names are not descriptive (p1, p1_conf, p1_dog, p2, p2_conf, p2_dog, p3, p3_conf, p3_dog)
- our shortest dataframe is api_tweets_df has only 2057 ids - which means we need to drop some ids from df_image_predictions for comparison

In [38]:
df_twitter_archive.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2356 entries, 0 to 2355
Data columns (total 17 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   tweet_id                    2356 non-null   int64
 1   in_reply_to_status_id       78 non-null     float64
 2   in_reply_to_user_id         78 non-null     float64
 3   timestamp                   2356 non-null   object
 4   source                      2356 non-null   object
 5   text                        2356 non-null   object
 6   retweeted_status_id         181 non-null    float64
 7   retweeted_status_user_id    181 non-null    float64
 8   retweeted_status_timestamp  181 non-null    object
 9   expanded_urls               2297 non-null   object
 10  rating_numerator            2356 non-null   int64
 11  rating_denominator          2356 non-null   int64
 12  name                        2356 non-null   object
 13  doggo                       2356 non-null   object
 14  floofer                     2356 non-null   object
 15  pupper                      2356 non-null   object
 16  puppo                       2356 non-null   object
dtypes: float64(4), int64(3), object(10)
memory usage: 313.0+ KB

- timestamp column is an object type, not a datetime type
- column numbers 1, 2, 6, 7, 8, and 9 all appear to have missing values (count is less than df length)
- our shortest dataframe is api_tweets_df has only 2057 ids - which means we need to drop some ids from df_twitter_archive for comparison

In [40]:
# checking to see if all of these are numbers and there isn't a random word thrown in
df_twitter_archive['rating_numerator'].unique()

array([  13,   12,   14,    5,   17,   11,   10,  420,  666,    6,   15,
        182,  960,    0,   75,    7,   84,    9,   24,    8,    1,   27,
          3,    4,  165, 1776,  204,   50,   99,   80,   45,   60,   44,
        143,  121,   20,   26,    2,  144,   88], dtype=int64)

In [41]:
# checking to see if all of these are numbers and there isn't a random word thrown in
df_twitter_archive['rating_denominator'].unique()

array([ 10,   0,  15,  70,   7,  11, 150, 170,  20,  50,  90,  80,  40,
       130, 110,  16, 120,   2], dtype=int64)

In [44]:
# takes a look at all the dog names
df_twitter_archive['name'].unique()

array(['Phineas', 'Tilly', 'Archie', 'Darla', 'Franklin', 'None', 'Jax',
       'Zoey', 'Cassie', 'Koda', 'Bruno', 'Ted', 'Stuart', 'Oliver',
       'Jim', 'Zeke', 'Ralphus', 'Canela', 'Gerald', 'Jeffrey', 'such',
       'Maya', 'Mingus', 'Derek', 'Roscoe', 'Waffles', 'Jimbo', 'Maisey',
       'Lilly', 'Earl', 'Lola', 'Kevin', 'Yogi', 'Noah', 'Bella',
       'Grizzwald', 'Rusty', 'Gus', 'Stanley', 'Alfy', 'Koko', 'Rey',
       'Gary', 'a', 'Elliot', 'Louis', 'Jesse', 'Romeo', 'Bailey',
       'Duddles', 'Jack', 'Emmy', 'Steven', 'Beau', 'Snoopy', 'Shadow',
       'Terrance', 'Aja', 'Penny', 'Dante', 'Nelly', 'Ginger', 'Benedict',
       'Venti', 'Goose', 'Nugget', 'Cash', 'Coco', 'Jed', 'Sebastian',
       'Walter', 'Sierra', 'Monkey', 'Harry', 'Kody', 'Lassie', 'Rover',
       'Napolean', 'Dawn', 'Boomer', 'Cody', 'Rumble', 'Clifford',
       'quite', 'Dewey', 'Scout', 'Gizmo', 'Cooper', 'Harold', 'Shikha',
       'Jamesy', 'Lili', 'Sammy', 'Meatball', 'Paisley', 'Albus',
       'Neptune', 'Quinn', 'Belle', 'Zooey', 'Dave', 'Jersey', 'Hobbes',
       'Burt', 'Lorenzo', 'Carl', 'Jordy', 'Milky', 'Trooper', 'Winston',
       'Sophie', 'Wyatt', 'Rosie', 'Thor', 'Oscar', 'Luna', 'Callie',
       'Cermet', 'George', 'Marlee', 'Arya', 'Einstein', 'Alice',
       'Rumpole', 'Benny', 'Aspen', 'Jarod', 'Wiggles', 'General',
       'Sailor', 'Astrid', 'Iggy', 'Snoop', 'Kyle', 'Leo', 'Riley',
       'Gidget', 'Noosh', 'Odin', 'Jerry', 'Charlie', 'Georgie', 'Rontu',
       'Cannon', 'Furzey', 'Daisy', 'Tuck', 'Barney', 'Vixen', 'Jarvis',
       'Mimosa', 'Pickles', 'Bungalo', 'Brady', 'Margo', 'Sadie', 'Hank',
       'Tycho', 'Stephan', 'Indie', 'Winnie', 'Bentley', 'Ken', 'Max',
       'Maddie', 'Pipsy', 'Monty', 'Sojourner', 'Odie', 'Arlo', 'Sunny',
       'Vincent', 'Lucy', 'Clark', 'Mookie', 'Meera', 'Buddy', 'Ava',
       'Rory', 'Eli', 'Ash', 'Tucker', 'Tobi', 'Chester', 'Wilson',
       'Sunshine', 'Lipton', 'Gabby', 'Bronte', 'Poppy', 'Rhino',
       'Willow', 'not', 'Orion', 'Eevee', 'Smiley', 'Logan', 'Moreton',
       'Klein', 'Miguel', 'Emanuel', 'Kuyu', 'Dutch', 'Pete', 'Scooter',
       'Reggie', 'Kyro', 'Samson', 'Loki', 'Mia', 'Malcolm', 'Dexter',
       'Alfie', 'Fiona', 'one', 'Mutt', 'Bear', 'Doobert', 'Beebop',
       'Alexander', 'Sailer', 'Brutus', 'Kona', 'Boots', 'Ralphie',
       'Phil', 'Cupid', 'Pawnd', 'Pilot', 'Ike', 'Mo', 'Toby', 'Sweet',
       'Pablo', 'Nala', 'Balto', 'Crawford', 'Gabe', 'Mattie', 'Jimison',
       'Hercules', 'Duchess', 'Harlso', 'Sampson', 'Sundance', 'Luca',
       'Flash', 'Finn', 'Peaches', 'Howie', 'Jazzy', 'Anna', 'Bo',
       'Seamus', 'Wafer', 'Chelsea', 'Tom', 'Moose', 'Florence', 'Autumn',
       'Dido', 'Eugene', 'Herschel', 'Strudel', 'Tebow', 'Chloe', 'Betty',
       'Timber', 'Binky', 'Dudley', 'Comet', 'Larry', 'Levi', 'Akumi',
       'Titan', 'Olivia', 'Alf', 'Oshie', 'Bruce', 'Chubbs', 'Sky',
       'Atlas', 'Eleanor', 'Layla', 'Rocky', 'Baron', 'Tyr', 'Bauer',
       'Swagger', 'Brandi', 'Mary', 'Moe', 'Halo', 'Augie', 'Craig',
       'Sam', 'Hunter', 'Pavlov', 'Maximus', 'Wallace', 'Ito', 'Milo',
       'Ollie', 'Cali', 'Lennon', 'incredibly', 'Major', 'Duke',
       'Reginald', 'Sansa', 'Shooter', 'Django', 'Diogi', 'Sonny',
       'Philbert', 'Marley', 'Severus', 'Ronnie', 'Anakin', 'Bones',
       'Mauve', 'Chef', 'Doc', 'Sobe', 'Longfellow', 'Mister', 'Iroh',
       'Baloo', 'Stubert', 'Paull', 'Timison', 'Davey', 'Pancake',
       'Tyrone', 'Snicku', 'Ruby', 'Brody', 'Rizzy', 'Mack', 'Butter',
       'Nimbus', 'Laika', 'Dobby', 'Juno', 'Maude', 'Lily', 'Newt',
       'Benji', 'Nida', 'Robin', 'Monster', 'BeBe', 'Remus', 'Mabel',
       'Misty', 'Happy', 'Mosby', 'Maggie', 'Leela', 'Ralphy', 'Brownie',
       'Meyer', 'Stella', 'mad', 'Frank', 'Tonks', 'Lincoln', 'Oakley',
       'Dale', 'Rizzo', 'Arnie', 'Pinot', 'Dallas', 'Hero', 'Frankie',
       'Stormy', 'Mairi', 'Loomis', 'Godi', 'Kenny', 'Deacon', 'Timmy',
       'Harper', 'Chipson', 'Combo', 'Dash', 'Bell', 'Hurley', 'Jay',
       'Mya', 'Strider', 'an', 'Wesley', 'Solomon', 'Huck', 'very', 'O',
       'Blue', 'Finley', 'Sprinkles', 'Heinrich', 'Shakespeare', 'Fizz',
       'Chip', 'Grey', 'Roosevelt', 'Gromit', 'Willem', 'Dakota', 'Dixie',
       'Al', 'Jackson', 'just', 'Carbon', 'DonDon', 'Kirby', 'Lou',
       'Nollie', 'Chevy', 'Tito', 'Louie', 'Rupert', 'Rufus', 'Brudge',
       'Shadoe', 'Colby', 'Angel', 'Brat', 'Tove', 'my', 'Aubie', 'Kota',
       'Eve', 'Glenn', 'Shelby', 'Sephie', 'Bonaparte', 'Albert',
       'Wishes', 'Rose', 'Theo', 'Rocco', 'Fido', 'Emma', 'Spencer',
       'Lilli', 'Boston', 'Brandonald', 'Corey', 'Leonard', 'Chompsky',
       'Beckham', 'Devón', 'Gert', 'Watson', 'Rubio', 'Keith', 'Dex',
       'Carly', 'Ace', 'Tayzie', 'Grizzie', 'Fred', 'Gilbert', 'Zoe',
       'Stewie', 'Calvin', 'Lilah', 'Spanky', 'Jameson', 'Piper',
       'Atticus', 'Blu', 'Dietrich', 'Divine', 'Tripp', 'his', 'Cora',
       'Huxley', 'Keurig', 'Bookstore', 'Linus', 'Abby', 'Shaggy',
       'Shiloh', 'Gustav', 'Arlen', 'Percy', 'Lenox', 'Sugar', 'Harvey',
       'Blanket', 'actually', 'Geno', 'Stark', 'Beya', 'Kilo', 'Kayla',
       'Maxaroni', 'Doug', 'Edmund', 'Aqua', 'Theodore', 'Chase',
       'getting', 'Rorie', 'Simba', 'Charles', 'Bayley', 'Axel',
       'Storkson', 'Remy', 'Chadrick', 'Kellogg', 'Buckley', 'Livvie',
       'Terry', 'Hermione', 'Ralpher', 'Aldrick', 'this', 'unacceptable',
       'Rooney', 'Crystal', 'Ziva', 'Stefan', 'Pupcasso', 'Puff',
       'Flurpson', 'Coleman', 'Enchilada', 'Raymond', 'all', 'Rueben',
       'Cilantro', 'Karll', 'Sprout', 'Blitz', 'Bloop', 'Lillie',
       'Ashleigh', 'Kreggory', 'Sarge', 'Luther', 'Ivar', 'Jangle',
       'Schnitzel', 'Panda', 'Berkeley', 'Ralphé', 'Charleson', 'Clyde',
       'Harnold', 'Sid', 'Pippa', 'Otis', 'Carper', 'Bowie',
       'Alexanderson', 'Suki', 'Barclay', 'Skittle', 'Ebby', 'Flávio',
       'Smokey', 'Link', 'Jennifur', 'Ozzy', 'Bluebert', 'Stephanus',
       'Bubbles', 'old', 'Zeus', 'Bertson', 'Nico', 'Michelangelope',
       'Siba', 'Calbert', 'Curtis', 'Travis', 'Thumas', 'Kanu', 'Lance',
       'Opie', 'Kane', 'Olive', 'Chuckles', 'Staniel', 'Sora', 'Beemo',
       'Gunner', 'infuriating', 'Lacy', 'Tater', 'Olaf', 'Cecil', 'Vince',
       'Karma', 'Billy', 'Walker', 'Rodney', 'Klevin', 'Malikai',
       'Bobble', 'River', 'Jebberson', 'Remington', 'Farfle', 'Jiminus',
       'Clarkus', 'Finnegus', 'Cupcake', 'Kathmandu', 'Ellie', 'Katie',
       'Kara', 'Adele', 'Zara', 'Ambrose', 'Jimothy', 'Bode', 'Terrenth',
       'Reese', 'Chesterson', 'Lucia', 'Bisquick', 'Ralphson', 'Socks',
       'Rambo', 'Rudy', 'Fiji', 'Rilo', 'Bilbo', 'Coopson', 'Yoda',
       'Millie', 'Chet', 'Crouton', 'Daniel', 'Kaia', 'Murphy', 'Dotsy',
       'Eazy', 'Coops', 'Fillup', 'Miley', 'Charl', 'Reagan', 'Yukon',
       'CeCe', 'Cuddles', 'Claude', 'Jessiga', 'Carter', 'Ole', 'Pherb',
       'Blipson', 'Reptar', 'Trevith', 'Berb', 'Bob', 'Colin', 'Brian',
       'Oliviér', 'Grady', 'Kobe', 'Freddery', 'Bodie', 'Dunkin', 'Wally',
       'Tupawc', 'Amber', 'Edgar', 'Teddy', 'Kingsley', 'Brockly',
       'Richie', 'Molly', 'Vinscent', 'Cedrick', 'Hazel', 'Lolo', 'Eriq',
       'Phred', 'the', 'Oddie', 'Maxwell', 'Geoff', 'Covach', 'Durg',
       'Fynn', 'Ricky', 'Herald', 'Lucky', 'Ferg', 'Trip', 'Clarence',
       'Hamrick', 'Brad', 'Pubert', 'Frönq', 'Derby', 'Lizzie', 'Ember',
       'Blakely', 'Opal', 'Marq', 'Kramer', 'Barry', 'Gordon', 'Baxter',
       'Mona', 'Horace', 'Crimson', 'Birf', 'Hammond', 'Lorelei', 'Marty',
       'Brooks', 'Petrick', 'Hubertson', 'Gerbald', 'Oreo', 'Bruiser',
       'Perry', 'Bobby', 'Jeph', 'Obi', 'Tino', 'Kulet', 'Sweets', 'Lupe',
       'Tiger', 'Jiminy', 'Griffin', 'Banjo', 'Brandy', 'Lulu', 'Darrel',
       'Taco', 'Joey', 'Patrick', 'Kreg', 'Todo', 'Tess', 'Ulysses',
       'Toffee', 'Apollo', 'Asher', 'Glacier', 'Chuck', 'Champ', 'Ozzie',
       'Griswold', 'Cheesy', 'Moofasa', 'Hector', 'Goliath', 'Kawhi',
       'by', 'Emmie', 'Penelope', 'Willie', 'Rinna', 'Mike', 'William',
       'Dwight', 'Evy', 'officially', 'Rascal', 'Linda', 'Tug', 'Tango',
       'Grizz', 'Jerome', 'Crumpet', 'Jessifer', 'Izzy', 'Ralph', 'Sandy',
       'Humphrey', 'Tassy', 'Juckson', 'Chuq', 'Tyrus', 'Karl',
       'Godzilla', 'Vinnie', 'Kenneth', 'Herm', 'Bert', 'Striker',
       'Donny', 'Pepper', 'Bernie', 'Buddah', 'Lenny', 'Arnold', 'Zuzu',
       'Mollie', 'Laela', 'Tedders', 'Superpup', 'Rufio', 'Jeb', 'Rodman',
       'Jonah', 'Chesney', 'life', 'Henry', 'Bobbay', 'Mitch', 'Kaiya',
       'Acro', 'Aiden', 'Obie', 'Dot', 'Shnuggles', 'Kendall', 'Jeffri',
       'Steve', 'Mac', 'Fletcher', 'Kenzie', 'Pumpkin', 'Schnozz',
       'Gustaf', 'Cheryl', 'Ed', 'Leonidas', 'Norman', 'Caryl', 'Scott',
       'Taz', 'Darby', 'Jackie', 'light', 'Jazz', 'Franq', 'Pippin',
       'Rolf', 'Snickers', 'Ridley', 'Cal', 'Bradley', 'Bubba', 'Tuco',
       'Patch', 'Mojo', 'Batdog', 'Dylan', 'space', 'Mark', 'JD',
       'Alejandro', 'Scruffers', 'Pip', 'Julius', 'Tanner', 'Sparky',
       'Anthony', 'Holly', 'Jett', 'Amy', 'Sage', 'Andy', 'Mason',
       'Trigger', 'Antony', 'Creg', 'Traviss', 'Gin', 'Jeffrie', 'Danny',
       'Ester', 'Pluto', 'Bloo', 'Edd', 'Willy', 'Herb', 'Damon',
       'Peanut', 'Nigel', 'Butters', 'Sandra', 'Fabio', 'Randall', 'Liam',
       'Tommy', 'Ben', 'Raphael', 'Julio', 'Andru', 'Kloey', 'Shawwn',
       'Skye', 'Kollin', 'Ronduh', 'Billl', 'Saydee', 'Dug', 'Tessa',
       'Sully', 'Kirk', 'Ralf', 'Clarq', 'Jaspers', 'Samsom', 'Harrison',
       'Chaz', 'Jeremy', 'Jaycob', 'Lambeau', 'Ruffles', 'Amélie', 'Bobb',
       'Banditt', 'Kevon', 'Winifred', 'Hanz', 'Churlie', 'Zeek',
       'Timofy', 'Maks', 'Jomathan', 'Kallie', 'Marvin', 'Spark',
       'Gòrdón', 'Jo', 'DayZ', 'Jareld', 'Torque', 'Ron', 'Skittles',
       'Cleopatricia', 'Erik', 'Stu', 'Tedrick', 'Filup', 'Kial',
       'Naphaniel', 'Dook', 'Hall', 'Philippe', 'Biden', 'Fwed',
       'Genevieve', 'Joshwa', 'Bradlay', 'Clybe', 'Keet', 'Carll',
       'Jockson', 'Josep', 'Lugan', 'Christoper'], dtype=object)

- some of these are obviously not names - such as "a", "actually", "all", "None", "not", "incredibly", "very", "my", "his", "this", etc. (will be further examined in cleaning)

In [39]:
api_tweets_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2057 entries, 0 to 2056
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   tweet_id        2057 non-null   int64
 1   retweet_count   2057 non-null   int64
 2   favorite_count  2057 non-null   int64
dtypes: int64(3)
memory usage: 48.3 KB

In [48]:
df_twitter_archive['doggo'].unique()

array(['None', 'doggo'], dtype=object)

In [50]:
df_twitter_archive['floofer'].unique()

array(['None', 'floofer'], dtype=object)

In [51]:
df_twitter_archive['pupper'].unique()

array(['None', 'pupper'], dtype=object)

In [49]:
df_twitter_archive['puppo'].unique()

array(['None', 'puppo'], dtype=object)

- All four of the above columns are essentially empty, even though they don't show NaN. This is pointless and might as well be deleted altogether.

### Initial assessment summary:

#### Quality Issues:
<ol>
    <li>NaN values in "df_image_predictions" dataframe</li>
    <br/>
    <li>NaN values in "df_twitter_archive" dataframe</li>
    <br/>
    <li>Remove ids missing from "api_tweets_df" from "df_image_predictions"</li>
    <br/>
    <li>Remove ids missing from "api_tweets_df" from "df_twitter_archive"</li>
    <br/>
    <li>Column names in "df_image_predictions" are not descriptive</li>
    <br/>
    <li>In "df_twitter_archive", "Timestamp" column is just a string/object, not a datetime type</li>
    <br/>
    <li>In "df_twitter_archive" "name" column - several values are obviously not names (see list in above bullet point) </li>
    <br/>
    <li>In "df_twitter_archive", tweet ids are listed in descending order (other two dataframes are listed in tweet id ascending order)</li>
    <br/>
    <li>"In df_image_predictions", breed names are not uniform in their casing and spacing</li>
</ol>

#### Tidiness Issues:
<ol>
    <li>"df_twitter_archive" timestamp can be separated into year, month, day, time</li>
    <br/>
    <li>"df_twitter_archive" columns "doggo", "floofer", "pupper", and "puppo" have "None" listed for all values. These columns hold no value and should just be dropped. (Tidiness issue because columns should store variables and these columns store nothing). </li>
    <br/>
    <li>"df_twitter_archive" can be separated to enhance tidiness into a dataframe with tweet_ids and text, and a dataframe with tweet_id and ratings. Could be even further separated into tweet_id and name, tweet_id and timestamp, tweet_id and url, etc. </li>
    <br/>
    <li>Make a clean master dataframe</li>
</ol>

# Clean

### First, I'll make a copy of each original dataframe to clean.

In [52]:
clean_twitter_archive = df_twitter_archive.copy()

In [53]:
clean_image_predictions = df_image_predictions.copy()

In [54]:
clean_api_tweets = api_tweets_df.copy()

#### Quality issue #1

#### Define

#### Code

#### Test

### Define

### Code

### Test